name: reusable docker

on:
  workflow_call:
    inputs:
      image_name: 
        type: string
        required: true
      tags:
        type: string
        required: true
    outputs:
      image_url:
        description: "The primary tagged Docker image URL"
        value: ${{ jobs.build.outputs.url }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.set-url.outputs.url }}
    steps:
      # Official actions/checkout v4.2.2 SHA
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # Official docker/setup-buildx-action v3.10.0 SHA
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318a742a1855737f099bb2c762c330c1e

      # Official docker/login-action v3.3.0 SHA
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Format tags cleanly
      - name: Format Docker Tags
        id: format-tags
        run: |
          FORMATTED_TAGS=$(echo '${{ inputs.tags }}' | jq -r '.[] | "${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:" + .')
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo "$FORMATTED_TAGS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Official docker/build-push-action v6.15.0 SHA
      - name: Build and Push Docker Image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: .
          no-cache: true
          push: true
          tags: ${{ steps.format-tags.outputs.tags }}

      # Expose output url to orchestration jobs
      - name: Set Output URL
        id: set-url
        run: |
          FIRST_TAG=$(echo '${{ inputs.tags }}' | jq -r '.[0]')
          echo "url=${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:$FIRST_TAG" >> "$GITHUB_OUTPUT"
